/* Profile */
const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'
const RESET_PROFILE = 'RESET_PROFILE'
const SET_PROFILE_INFO = 'SET_PROFILE_INFO'
const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
const REGISTER_FAILURE = 'REGISTER_FAILURE'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILURE = 'LOGIN_FAILURE'
const SET_SESSION_TOKEN = 'SET_SESSION_TOKEN'
const REMOVE_SESSION_TOKEN = 'REMOVE_SESSION_TOKEN'

/* Users */
const SET_FOUND_ACTIVE_USER = 'SET_FOUND_ACTIVE_USER'
const SET_ACTIVE_USER = 'SET_ACTIVE_USER'
const SET_USERS = 'SET_USERS'
const SET_USER = 'SET_USER'

/* Device */
const SET_DEVICE_SETTINGS = 'SET_DEVICE_SETTINGS'

export default {
  SET_SEARCH_RESULTS,
  SET_SEARCH_QUERY,

  RESET_PROFILE,
  SET_PROFILE_INFO,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  SET_SESSION_TOKEN,
  REMOVE_SESSION_TOKEN,

  SET_FOUND_ACTIVE_USER,
  SET_ACTIVE_USER,
  SET_USERS,
  SET_USER,
  SET_DEVICE_SETTINGS
}
